// Auth
export const START_LOGIN = "START_LOGIN";
export const LOGIN_SUCCESSFULL = "LOGIN_SUCCESSFULL";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const START_SIGNUP = "START_SIGN_UP";
export const SIGNUP_SUCCESSFULL = "SIGN_UP_SUCCESSFULL";
export const SIGNUP_FAILED = "SIGN_UP_FAILED";
export const CLEAR_STATE = "CLEAR_STATE";
export const LOGOUT = "LOGOUT";
export const AUTHENTICATE_USER = "AUTHENTICATE_USER";
export const GET_GROUP_SUCESS = "GET_GROUP_SUCESS";
export const GET_GROUP_FAILED = "GET_GROUP_FAILED";

// Guest
export const GUEST_LOGIN = "GUEST_LOGIN";

// Room
export const START_ROOM = "START_ROOM";
export const ROOM_SUCCESSFULL = "ROOM_SUCCESSFULL";
export const ROOM_FAILED = "ROOM_FAILED";
export const CLEAR_ROOM = "CLEAR_ROOM";

// group
export const GROUP_SUCCESS = "GROUP_SUCCESS";
export const GROUP_FAILED = "GROUP_FAILED";
export const GROUP_START = "GROUP_START";
export const CLEAR_GROUP_STATE = "CLEAR_GROUP_STATE";

//message
export const START_MESSAGE = "START_MESSAGE";
export const MESSAGE_FAILED = "MESSAGE_FAILED";
export const MESSAGE_SUCCESS = "MESSAGE_SUCCESS";
export const CLEAR_MESSAGE_STATE = "CLEAR_MESSAGE_STATE";

//socket
export const START_SOCKET = "START_SOCKET";
export const SOCKET_SUCCESS = "SOCKET_SUCCESS";
export const SOCKET_FAILED = "SOCKET_FAILED";
export const CLEAR_SOCKET_STATE = "CLEAR_SOCKET_STATE";
